### ISSUE TITLE
Update plan.

### ISSUE THREAD

**Issue by koba04** [MarionetteLabs/marionette-changelog-detail#3]
Do you have any plan to update this document?

Thank you for helpful document! :smile:

**Comment by jamesplease** [comment]
Yup @koba04 working on it now for the official release. :)

**Comment by jamesplease** [comment]
Also, it will likely be tagged and kept up-to-date with the actual releases of Marionette. It might even find itself in the Marionette org one day.

Going to close this issue, unless you have any other Q's? :)

**Comment by koba04** [comment]
Great! :+1:
